// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id,user_id,expires_at) VALUES ($1,$2,$3)
`

type CreateSessionParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO refresh_tokens (hash,session_id) VALUES ($1,$2)
`

type CreateTokenParams struct {
	Hash      []byte
	SessionID pgtype.UUID
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken, arg.Hash, arg.SessionID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password_hash) VALUES ($1,$2,$3,$4) RETURNING id, name, email, password_hash
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const lockSession = `-- name: LockSession :one
SELECT id, user_id, expires_at, revoked FROM sessions WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked=true WHERE id=$1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const tokenByHash = `-- name: TokenByHash :one
SELECT hash, session_id, used_at FROM refresh_tokens WHERE hash=$1
`

func (q *Queries) TokenByHash(ctx context.Context, hash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, tokenByHash, hash)
	var i RefreshToken
	err := row.Scan(&i.Hash, &i.SessionID, &i.UsedAt)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $2 WHERE id = $1 RETURNING id, name, email, password_hash
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const useToken = `-- name: UseToken :exec
UPDATE refresh_tokens SET used_at=$2 WHERE hash=$1
`

type UseTokenParams struct {
	Hash   []byte
	UsedAt pgtype.Timestamptz
}

func (q *Queries) UseToken(ctx context.Context, arg UseTokenParams) error {
	_, err := q.db.Exec(ctx, useToken, arg.Hash, arg.UsedAt)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, name, email, password_hash FROM users WHERE email=$1
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, name, email, password_hash FROM users WHERE id=$1
`

func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}
