// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Url             string
	IntervalSeconds int32
	CreatedAt       pgtype.Timestamptz
}

type RefreshToken struct {
	Hash      []byte
	SessionID pgtype.UUID
	UsedAt    pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	AvatarUrl    string
}
