// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (id, user_id, url, interval_seconds)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, url, interval_seconds, created_at
`

type CreateMonitorParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Url             string
	IntervalSeconds int32
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.IntervalSeconds,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.IntervalSeconds,
		&i.CreatedAt,
	)
	return i, err
}
