// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (id, user_id, url, interval_seconds)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, url, interval_seconds, created_at, updated_at
`

type CreateMonitorParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Url             string
	IntervalSeconds int32
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.IntervalSeconds,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors WHERE id = $1 AND user_id = $2
`

type DeleteMonitorParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitor, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, user_id, url, interval_seconds, created_at, updated_at FROM monitors WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMonitors(ctx context.Context, userID pgtype.UUID) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.IntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET url = $3, interval_seconds = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, url, interval_seconds, created_at, updated_at
`

type UpdateMonitorParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Url             string
	IntervalSeconds int32
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.IntervalSeconds,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
